name: terraform destroy workflow

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_org_id: ${{ secrets.org_id }}
  TF_VAR_org_path: ${{ secrets.org_path }}
  TF_VAR_source_ssh_net: ${{ secrets.source_ssh_net }}
  TF_VAR_PUBLIC_KEY: ${{ secrets.public_key }}
  TF_VAR_account_id: ${{ secrets.account_id }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
  BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
  DO_SPACES_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY_ID }}
  DO_SPACES_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_ACCESS_KEY }}
  
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: terraform init
        run: |
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=$BUCKET_KEY" \
            -backend-config="endpoint=$BUCKET_ENDPOINT" \
            -backend-config="access_key=$DO_SPACES_ACCESS_KEY_ID" \
            -backend-config="secret_key=$DO_SPACES_SECRET_ACCESS_KEY"
      - name: terraform destroy
        run: |
          terraform destroy -auto-approve