name: terraform apply workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_ORG_ID: ${{ secrets.ORG_ID }}
  TF_VAR_ORG_PATH: ${{ secrets.ORG_PATH }}
  TF_VAR_SOURCE_SSH_NET: ${{ secrets.SOURCE_SSH_NET }}
  TF_VAR_PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
  TF_VAR_ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
  BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
  DO_SPACES_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_KEY_ID }}
  DO_SPACES_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET_ACCESS_KEY }}
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for `skip-tf-apply` label
        id: check_label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_LABELS=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels[].name')
          if [[ "$PR_LABELS" == *"skip-tf-apply"* ]]; then
            echo "Label 'skip-tf-apply' detected. Skipping apply step."
            echo "skip_apply=true" >> $GITHUB_ENV
          else
            echo "skip_apply=false" >> $GITHUB_ENV
          fi

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.7

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=$BUCKET_KEY" \
            -backend-config="endpoint=$BUCKET_ENDPOINT" \
            -backend-config="access_key=$DO_SPACES_ACCESS_KEY_ID" \
            -backend-config="secret_key=$DO_SPACES_SECRET_ACCESS_KEY"

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: env.skip_apply != 'true'
        run: terraform apply -input=false tfplan